hand_left_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - hand_left_fingers_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 5.0
    hand_left_fingers_joint:
      goal: 0.02
