play_motion:
  motions:
    start_ari:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, head_1_joint, head_2_joint]
      points:
        - time_from_start: 0
          positions: [0.2013, 0.2118, 0.01, 0.13, 0.0, 0.1989, 0.1999, 0.0302, 0.15, 0.0, 0.0001, -0.0003]
        - time_from_start: 2
          positions: [-0.2005, 0.11, 0.0385, 0.4014, 0.0, -0.2007, 0.11, 0.051, 0.402, 0.0, 0, -0.0078]
      meta:
        name: Start ARI
        usage: Position
        description: Default ARI position
    bow:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, head_1_joint, head_2_joint]
      points:
        - time_from_start: 0
          positions: [-0.201, 0.11, 0.0372, 0.4028, 0.0, -0.2014, 0.11, 0.0462, 0.404, 0.0, 0, -0.0078]
        - time_from_start: 2
          positions: [-0.403, 0.11, 0.0365,  0.2869, 0.0, -0.4006, 0.11, 0.0496, 0.3064, 0.0, -0.0001, 0.2957]
        - time_from_start: 2.5
          positions: [-0.403, 0.11, 0.0365, 0.2869, 0.0, -0.4006, 0.11, 0.0496, 0.3064, 0.0, -0.0001, 0.2957]
        - time_from_start: 3.5
          positions: [-0.201, 0.11, 0.0372, 0.4028, 0.0, -0.2014, 0.11, 0.0462, 0.404, 0.0, 0, -0.0078]
      meta:
        name: Bow
        usage: Entertainment
        description: Bow the head
    wave:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint]
      points:
        - time_from_start: 0
          positions: [-0.20, 0.11, 0.0362, 0.4042, 0.0, -0.2021, 0.11, 0.0419, 0.4059, 0.0]
        - time_from_start: 2.5
          positions: [-0.20, 0.17, 0.0383, 0.4018, 0.0, -0.2108, 1.58, 1.84, 0.4113, 0.0]
        - time_from_start: 4
          positions: [-0.20, 0.17, 0.0384, 0.4019, 0.0, -0.222, 1.58, 1.84, 1.49, 0.0]
        - time_from_start: 5
          positions: [-0.20, 0.17, 0.0385, 0.4018, 0.0, -0.2216, 1.58, 1.84, 1.0, 0.0]
        - time_from_start: 6
          positions: [-0.20, 0.17, 0.0373, 0.4035, 0.0, -0.224, 1.58, 1.84, 1.49, 0.0]
        - time_from_start: 7.5
          positions: [-0.20, 0.17, 0.0383, 0.4018, 0.0, -0.2108, 1.58, 1.84, 0.4113, 0.0]
        - time_from_start: 10
          positions: [-0.20, 0.11, 0.0362, 0.4042, 0.0, -0.2021, 0.11, 0.0419, 0.4059, 0.0]
      meta:
        name: Wave
        usage: Entertainment
        description: Wave right hand
    look_around:
      joints: [head_1_joint, head_2_joint]
      points:
        - time_from_start: 0
          positions: [-0.0002, -0.008]
        - time_from_start: 2
          positions: [-0.9417, 0.1285]
        - time_from_start: 6
          positions: [0.9417, 0.1285]
        - time_from_start: 8
          positions: [-0.0002, -0.008]
      meta:
        name: Look Around
        usage: Entertainment
        description: Look around itself
    nod:
      joints: [head_1_joint, head_2_joint]
      points:
        - time_from_start: 0
          positions: [-0.0002, -0.007]
        - time_from_start: 0.5
          positions: [0, -0.1597]
        - time_from_start: 1.2
          positions: [-0.0001, 0.165]
        - time_from_start: 2.2
          positions: [-0.0002, -0.007]
      meta:
        name: Nod
        usage: Entertainment
        description: Nod head
    show_left:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, head_1_joint, head_2_joint]
      points:
        - time_from_start: 0
          positions: [-0.202, 0.11, 0.0351, 0.4055, 0.0, -0.2009, 0.11, 0.0298, 0.4038, 0.0, -0.0003, -0.007]
        - time_from_start: 2
          positions: [0.52, 0.18, 1.0512, 0.2548, 0.0, -0.1985, 0.24, -0.5604, 0.3982, 0.0, 0.5204, 0.0895]
        - time_from_start: 3.5
          positions: [-0.202, 0.11, 0.0351, 0.4055, 0.0, -0.2009, 0.11, 0.0298, 0.4038, 0.0, -0.0003, -0.007]
      meta:
        name: Show Left
        usage: Entertainment
        description: Point to the left
    show_right:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, head_1_joint, head_2_joint]
      points:
        - time_from_start: 0
          positions: [-0.2009, 0.11, 0.0298, 0.4038, 0.0, -0.202, 0.11, 0.0351, 0.4055, 0.0, -0.0003, -0.007]
        - time_from_start: 2
          positions: [-0.1985, 0.24, -0.5604, 0.3982, 0.0, 0.5299, 0.18, 1.0512, 0.2548, 0.0, -0.5204, 0.0895]
        - time_from_start: 3.5
          positions: [-0.2009, 0.11, 0.0298, 0.4038, 0.0, -0.202, 0.11, 0.0351, 0.4055, 0.0, -0.0003, -0.007]
      meta:
        name: Show Right
        usage: Entertainment
        description: Point to the right
    shake_right:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint]
      points:
        - time_from_start: 0
          positions: [-0.201, 0.11, 0.0365, 0.4028, 0.0, -0.2014, 0.11, 0.0462, 0.404, 0.0]
        - time_from_start: 2.5
          positions: [-0.2016, 0.11, 0.0347, 0.4042, 0.0, 0.2014, 0.2399, 0.0899, 1.5, 0.0]
        - time_from_start: 2.7
          positions: [-0.2016, 0.11, 0.0347, 0.4042, 0.0, 0.2014, 0.2399, 0.0899, 1.5, 0.0]
        - time_from_start: 3.7
          positions: [-0.202, 0.11, 0.0332, 0.4055, 0.0, 0.2014, 0.2399, 0.09, 1.3, 0.0]
        - time_from_start: 4.7
          positions: [-0.2016, 0.11, 0.0347, 0.4042, 0.0, 0.2014, 0.2399, 0.0899, 1.5, 0.0]
        - time_from_start: 5.7
          positions: [-0.202, 0.11, 0.0332, 0.4055, 0.0, 0.2014, 0.2399, 0.09, 1.3, 0.0]
        - time_from_start: 5.8
          positions: [-0.202, 0.11, 0.0332, 0.4055, 0.0, 0.2014, 0.2399, 0.09, 1.3, 0.0]
        - time_from_start: 7.8
          positions: [-0.201, 0.11, 0.0365, 0.4028, 0.0, -0.2014, 0.11, 0.0462, 0.404, 0.0]
      meta:
        name: Shake Right
        usage: Entertainment
        description: Shake right hand
    shake_left:
      joints: [arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint]
      points:
        - time_from_start: 0
          positions: [-0.201, 0.11, 0.0365, 0.4028, 0.0, -0.2014, 0.11, 0.0462, 0.404, 0.0]
        - time_from_start: 2.5
          positions: [-0.2016, 0.11, 0.0347, 0.4042, 0.0, 0.2014, 0.2399, 0.0899, 1.5, 0.0]
        - time_from_start: 2.7
          positions: [-0.2016, 0.11, 0.0347, 0.4042, 0.0, 0.2014, 0.2399, 0.0899, 1.5, 0.0]
        - time_from_start: 3.7
          positions: [-0.202, 0.11, 0.0332, 0.4055, 0.0, 0.2014, 0.2399, 0.09, 1.3, 0.0]
        - time_from_start: 4.7
          positions: [-0.2016, 0.11, 0.0347, 0.4042, 0.0, 0.2014, 0.2399, 0.0899, 1.5, 0.0]
        - time_from_start: 5.7
          positions: [-0.202, 0.11, 0.0332, 0.4055, 0.0, 0.2014, 0.2399, 0.09, 1.3, 0.0]
        - time_from_start: 5.8
          positions: [-0.202, 0.11, 0.0332, 0.4055, 0.0, 0.2014, 0.2399, 0.09, 1.3, 0.0]
        - time_from_start: 7.8
          positions: [-0.201, 0.11, 0.0365, 0.4028, 0.0, -0.2014, 0.11, 0.0462, 0.404, 0.0]
      meta:
        name: Shake Left
        usage: Entertainment
        description: Shake left hand
##################### Alive motions #########################################################
    alive_1:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint]
      points:
        - time_from_start: 0
          positions: [-0.2811, 0.11, 0.1611, 0.493, 0.0, -0.199, 0.13, -0.1354, 0.3981, 0.0]
    alive_2:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint]
      points:
        - time_from_start: 0
          positions: [0.0824, 0.11, 0.0314, 0.13, 0.0, -0.0777, 0.11, 0.0227, 0.2372, 0.0]
    alive_3:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, head_1_joint, head_2_joint]
      points:
        - time_from_start: 0
          positions: [-0.2007, 0.11, 0.0238, 0.1727, 0.0, -0.1996, 0.11, 0.0347, 0.6265, 0.0, 0.2475, 0.0705]
    alive_4:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, head_1_joint, head_2_joint]
      points:
        - time_from_start: 0
          positions: [-0.1996, 0.11, 0.0347, 0.6265, 0.0, -0.2007, 0.11, 0.0238, 0.1727, 0.0, -0.2475, 0.0705]
    alive_5:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint]
      points:
        - time_from_start: 0
          positions: [-0.201, 0.11, 0.0374, 0.4027, 0.0, -0.1999, 0.11, 0.0389, 0.3999, 0.0]
        - time_from_start: 1
          positions: [-0.0783, 0.11, 0.3, 0.2358, 0.0, -0.0783, 0.11, 0.3, 0.2358, 0.0]
        - time_from_start: 2
          positions: [-0.201, 0.11, 0.0374, 0.4027, 0.0, -0.1999, 0.11, 0.0389, 0.3999, 0.0]
    alive_6:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint]
      points:
        - time_from_start: 0
          positions: [-0.201, 0.11, 0.0374, 0.4027, 0.0, -0.1999, 0.11, 0.0388, 0.3999, 0.0]
        - time_from_start: 0.75
          positions: [-0.2015, 0.11, 0.0364, 0.4039, 0.0, 0.0841, 0.11, 0.011, 0.1665, 0.0]
        - time_from_start: 1.5
          positions: [0.0841, 0.11, 0.011, 0.1665, 0.0, -0.1999, 0.11, 0.0388, 0.3999, 0.0]
        - time_from_start: 2.25
          positions: [-0.2015, 0.11, 0.0364, 0.4039, 0.0, 0.0841, 0.11, 0.011, 0.1665, 0.0]
        - time_from_start: 3
          positions: [-0.201, 0.11, 0.0374, 0.4027, 0.0, -0.1999, 0.11, 0.0388, 0.3999, 0.0]
    alive_7:
      joints: [head_1_joint, head_2_joint]
      points:
        - time_from_start: 0.75
          positions: [0.2478, -0.0765]
        - time_from_start: 2
          positions: [-0.2138, -0.0796]
        - time_from_start: 2.75
          positions: [-0.0003, -0.0208]
    flying:
      joints: [arm_left_1_joint, arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint]
      points:
        - time_from_start: 0
          positions: [-0.19641, 0.095168, 0.038854, 0.39397, -0.0016249, -0.1972, 0.10209, 0.038679, 0.3883, -0.0043945]
        - time_from_start: 1.26
          positions: [0.34662, 0.093634, 0.040388, 0.36482, -0.0077609, 0.3627, 0.088289, 0.029476, 0.36683, -0.0028605]
        - time_from_start: 2
          positions: [-0.013865, 0.11358, 0.040388, 0.29426, -0.0016249, -0.025395, 0.17266, 0.029476, 0.29473, -0.0089964]
        - time_from_start: 2.74
          positions: [0.3006, 0.082896, 0.041922, 0.35102, -0.0062269, 0.31822, 0.086755, 0.027942, 0.35456, -0.0043945]
        - time_from_start: 3.5
          positions: [-0.013865, 0.11358, 0.040388, 0.29426, -0.0016249, -0.025395, 0.17266, 0.029476, 0.29473, -0.0089964]
      meta:
        name: Fly
        usage: Entertainment
        description: Wave both arms in front of the robot